# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ai-papers',
                'doc_host': 'https://melonkernel.github.io',
                'git_url': 'https://github.com/melonkernel/ai-papers',
                'lib_path': 'ai_papers'},
  'syms': {'ai_papers.core': {'ai_papers.core.foo': ('core.html#foo', 'ai_papers/core.py')}}}